### ISSUE TITLE
Dart Build have no version that matches >=0.10.0 <0.12.0

### ISSUE THREAD

**Issue by pratikpparikh** [dart-lang/build#675]
Hi Dart Community,

    I am trying to create a simple web app using dart 2.0.dev.8 and angular 5.0-alpha.  I get the following error "Package build has no versions that match >=0.10.0 <0.12.0 derived from:
- angular 5.0.0-alpha+1 depends on version >=0.10.0 <0.12.0
- angular_compiler 0.4.0-alpha+1 depends on version >=0.10.0 <0.12.0"  while doing get dependencies.  Below is what my pubsec.yaml looks like.  Please help me understand what I am doing wrong?

environment:
  sdk: '>=2.0.0-dev.8.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+1
  build: '>=0.10.0 <0.12.0'
  angular_forms: 1.0.1-alpha+1
  built_collection: ^1.6.0
  collection: ^1.14.0
  fixnum: ^0.10.5
  intl: '>=0.14.0 <0.16.0'
  js: ^0.6.1
  logging: ^0.11.2
  meta: ^1.0.4
  observable: '>=0.17.0+1 <0.21.0'
  perf_api: ^0.1.0
  quiver: '>=0.24.0 <0.26.0'
  sass_builder: ^1.0.1
  uuid: ^0.5.3
  angular_components: ^0.9.0-alpha+1

dev_dependencies:
  angular_test: ^1.0.2-alpha+1
  sass_builder: ^1.0.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

Regards,

**Comment by zoechi** [comment]
You mentioned in Gitter that this is fixed. Is it not?

**Comment by jakemac53** [comment]
Can you try doing a `pub upgrade` instead of a `pub get`. That seems to solve the issue for me although it doesn't really make sense.

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/pub/issues/1750 as well

**Comment by pratikpparikh** [comment]
@zoechi I reduced the scope of my pubspec so the problem is there but yes i got past it for now.  The issue still exists.  Sorry for any confusion.

**Comment by jakemac53** [comment]
I am going to close this in favor of https://github.com/dart-lang/pub/issues/1750, since we can't take any action on it.
